### ISSUE TITLE
Add more packages to the web search

### ISSUE THREAD

**Issue by tmcgilchrist** [camlspotter/ocamloscope#27]
What would be involved in getting more packages up on the website search? 
In particular I'd like to see `Core` and ideally all the packages in OPAM if that's possible.

**Comment by camlspotter** [comment]
Core was a part of search space in OCamlOScope 4.01, but it is out for technical reasons.

For this moment I cannot install Core via OPAM on Mac OS X.  See https://github.com/ocaml/opam/issues/2006 for details.  The packages depend on the libraries distributed from Jane Street (such as type-conv) fail to install due to this.  I want to wait the resolution of ticket rather than download the source archives manually.  

OCamlOScope has just moved to 4.02.1 base in the last weekend.  Number of searchable packages is currently small just because I have no time to build DB file scraping.  From the experience of 4.01 based OCamlOScope, I think I can provide the information of the Top 100 OPAM packages without problems in near future.

Covering *all* the OPAM packages in OCamlOScope is very hard for now.  DB building requires installation of each package, and I myself do not have enough resource to install all the packages: some require special library to build and some are system dependent.  We can ask opam-repository team to run OCamlOScope DB file building at their Travis check of packages probably...

**Comment by camlspotter** [comment]
Core is now in the search.

**Comment by tmcgilchrist** [comment]
Thanks
